source/_data/copy.yaml, source/_snippets/layout/footer.twig, source/_snippets/section/left_and_right.twig, source/_snippets/section/references.twig, source/css/manual-new-style.css, source/css/style.css, source/index.twig
=> styling for mobile

source/contact.twig, source/index.twig
Leave this great idea for later
=> Removing mentions about Rector CI

assets/css/app.css, assets/scss/app.scss, assets/scss/logo.scss, config/packages/twig.yaml, phpstan.neon, src/Twig/TitleTwigExtension.php, templates/_snippets/layout/footer.twig, templates/_snippets/layout/head.twig, templates/_snippets/layout/small_header.twig, templates/base.twig, templates/homepage/contact.twig, templates/homepage/homepage.twig
=> Mobile + headline tuning

templates/homepage/homepage.twig
=> Fix typos on homepage

.docker/php/xdebug.ini, .env, Dockerfile, composer.lock, config/services.yaml, docker-compose.dist.yml, ecs.yaml, src/Controller/DemoController.php, src/Entity/RectorRun.php, src/Form/RectorRunFormData.php, src/Form/RectorRunFormType.php, src/Process/RectorProcessRunner.php, src/Process/RectorRunFailedException.php, src/Repository/RectorRunRepository.php, symfony.lock, templates/homepage/demo.twig
=> WIP: Rector demo form

Dockerfile, bin/run-demo.sh, docker-compose.dist.yml, src/DemoRunner.php, src/Process/RectorProcessRunner.php
As well i improved docker build speed again.
=> Fix Docker security issue with sudo rm -rf

README.md, composer.json, composer.lock, phpstan.neon, src/Entity/RectorRun.php, src/Twig/RuleReadmeLinkTwigExtension.php, symfony.lock, templates/demo/demo.twig
Closes #103 
**Bonus:** rules are linked to the documentation! B-)
=> Show applied rules under the diff

assets/scss/app.scss, templates/homepage/contact.twig
=> Added david to contact page

packages/demo/src/Lint/ForbiddenPHPFunctionsChecker.php, packages/demo/tests/Lint/ForbiddenPHPFunctionsCheckerTest.php
Replaces ForbiddenPHPFunctionsCheckerTest
=> add ForbiddenPHPFunctionsCheckerTest

packages/demo/src/DemoRunner.php, symfony.lock
=> Fix sentry logging function name

packages/demo/src/Entity/RectorRun.php
=> Hotfix missing version in rector run

templates/_snippets/layout/footer.twig, templates/homepage/homepage.twig
The focus on sponsors is not giving back and no new sponsors for last couple of months.
=> drop sponsoring

composer.lock, config/bundles.php, packages/blog/data/_posts/2020/2020-04-16-how-to-migrate-from-phpexcel-to-phpspreadsheet-with-rector-in-30-minutes.md, symfony.lock
- bump
- update --set to config
=> --set update

src/Twig/RectorCountVariableProvider.php
Follow up to https://github.com/rectorphp/getrector.org/pull/187
=> fix Rector count

packages/blog/data/_posts/2020/2020-03-10-upgrading-glami-to-psr-4-what-why-how.md, packages/blog/data/_posts/2020/2020-10-05-how-to-make-rector-contribute-your-pull-requests-every-day.md, packages/blog/data/_posts/2020/2020-11-30-smooth-upgrade-to-php-8-in-diffs.md, templates/homepage/contact.twig
Closes https://github.com/rectorphp/getrector.org/issues/196
=> [post] Smooth Upgrade to PHP 8 in Diffs

assets/scss/app.scss, ecs.php, packages/demo/data/demo-config.php, packages/demo/src/Controller/DemoController.php, packages/demo/src/Entity/RectorRun.php, packages/demo/src/Form/DemoFormType.php, src/Twig/RuleReadmeLinkTwigExtension.php, templates/_snippets/javascripts.twig, templates/demo/demo.twig
=> Improve demo design

.env, docker-compose.yml
=> Resolve directory for demo temp files on host dynamically

.docker/docker-entrypoint, .gitignore, README.md, bin/pull-docker-images.sh, bin/run-from-docker.sh, docker-compose.dist.yml
This reverts commit 4a03bd7a249eae6b79b7a4f3716cb97f4fabac2e.
Hotfix for 2 Docker bugs on Linux:
- https://github.com/rectorphp/getrector.org/pull/251#issuecomment-777072338
- https://github.com/rectorphp/getrector.org/pull/254#issuecomment-777079386
Feel free to revert when a propper fix is ready. I need to make some fixes on demo form now, so I need working Docker form
=> Revert "Update docker setup (#251)"

.env, README.md, docker-compose.yml
=> Removed envfile from docker-compose

bin/run-demo.sh
=> Set size of terminal for demo output

README.md
=> Explain HOST_DEMO_DIR

README.md
Thanks to #268 we no longer need to run demo in extra docker container 🎉 
cc @ruudk
=> Update readme - remove no longer relevant information

packages/blog/templates/blog/blog.twig
Replaces https://github.com/rectorphp/getrector.org/pull/276
Ref https://github.com/rectorphp/getrector.org/issues/247
=> Add RSS link on blog page

assets/scss/app.scss, packages/blog/src/ValueObject/Post.php, packages/blog/templates/blog/post.twig, phpstan.neon
Closes https://github.com/rectorphp/getrector.org/issues/247
=> [blog] Add social share links

.github/workflows/production_build.yaml
ref https://github.com/rectorphp/getrector.org/pull/305#issuecomment-825126810 /cc @JanMikes
=> [Production Build] run composer update and commit

.github/workflows/production_build.yaml
ref https://github.com/rectorphp/getrector.org/pull/307#issuecomment-826102050
=> [GHA] Revert auto-commit

.github/workflows/daily_pull_request_automatic_update.yaml
By Add matrix.actions.name value ref https://github.com/rectorphp/getrector.org/pull/318#issuecomment-841622741
=> Update automatic daily pull request title

.github/workflows/per_three_day_pull_request_automatic_update.yaml
Fixes #327  refs https://github.com/rectorphp/getrector.org/pull/327#issuecomment-846382616
=> [GHA] Per-3 days automatic update rector/rector only dependency

assets/scss/app.scss, src/Controller/BookController.php, templates/_snippets/styles.twig, templates/blog/post.twig, templates/homepage/book.twig, templates/homepage/for_companies.twig, templates/homepage/homepage.twig
=> Add book link to homepage and above posts

templates/homepage/homepage.twig
- Closes https://github.com/rectorphp/getrector.org/issues/325
- Closes https://github.com/rectorphp/getrector.org/issues/227
<br>
This PR adds a new section, that explain what Rector is and how to add it:
=> Add description and action step to homepage

composer.lock
See https://twitter.com/doctrineproject/status/1396870093972332545
=> Use doctrine/orm 2.9 stable

.github/dependabot.yml
ref https://github.com/rectorphp/getrector.org/pull/338#issuecomment-850911245 Closes https://github.com/rectorphp/getrector.org/pull/338
=> Apply monthly schedule from dependabot

.github/workflows/daily_pull_request_automatic_update.yaml
to make github action running ref https://github.com/rectorphp/getrector.org/pull/385#issuecomment-866421904
=> use access token for daily create pull request

.github/workflows/production_build.yaml, .github/workflows/unit_tests.yaml
To avoid production build and Unit test gha hanging:
=> Specify branch main on production_build.yaml and unit_tests.yaml

.github/workflows/cache_warmup.yaml
ref https://github.com/rectorphp/getrector.org/pull/387#discussion_r657160052
=> use Cache warmup gha naming

packages/Demo/Entity/RectorRun.php, src/ValueObject/Error.php, templates/demo/demo.twig
Closes https://github.com/rectorphp/rector/issues/6592
<br>
---
---
=> Add type errors in demo run

templates/demo/demo.twig
Closes https://github.com/rectorphp/getrector.org/issues/419
=> remove dead link to params

composer.json
Update PHPStan require-dev to ^1.0
=> Prepare for PHPStan ^1.0

ecs.php, phpstan.neon, rector.php
Current demo page got 500 error on "Process" button clicked, this revert unregister `packages/Demo/data/DemoFile.php` from skip config.
This reverts commit 55dddf42c495b3106f29d98b5510c9f3390922c4.
=> Revert remove packages/data/demo/DemoFile.php from the skip config list

data/blog/posts/2021/2021-10-11-how-to-upgrade-annotations-to-attributes.md
Ref https://github.com/rectorphp/rector-symfony/pull/85/files
=> [blog] update aliases, add extra set

composer.json, composer.lock
So only update when there is new version.
=> [Dep] Update rector version to ^0.12.7

composer.lock, rector.php
- bump deps
- [rector] enable phpunit code quality set
=> [maintenance] Bump deps

composer.lock
Reverts rectorphp/getrector.org#460
demo page submit now errors  https://github.com/rectorphp/getrector.org/issues/461, 
it may related to it, revert one by one.
=> Revert [automated] Update Rector Dependencies

composer.json, composer.lock, config/bundles.php
Reverts rectorphp/getrector.org#459
Per issue https://github.com/rectorphp/getrector.org/issues/461
=> Revert Remove sensio fw

packages/Demo/Entity/RectorRun.php, phpstan.neon, rector.php
=> [cs] Use ORM alias for annotation naming

data/blog/posts/2022/2022-02-07-success-story-of-automated-framework-migration-from-fuelphp-to-laravel-of-400k-lines-application.md
- set date, add basic config header
- gram 1
=> [review] Migration Fuel to Laravel post Review

data/blog/posts/2020/2020-04-16-how-to-migrate-from-phpexcel-to-phpspreadsheet-with-rector-in-30-minutes.md, data/blog/posts/2020/2020-08-31-rector-is-moving-from-yaml-to-php-configs-what-changes-and-how-to-get-ready.md, data/blog/posts/2020/2020-11-30-smooth-upgrade-to-php-8-in-diffs.md, data/blog/posts/2020/2020-12-07-laravel-facades-to-constructor-injection-replace-facade-aliases-with-full-classes-in-2-hours.md, data/blog/posts/2020/2020-12-28-rector-09-released.md, data/blog/posts/2021/2021-01-11-switch-symfony-string-route-names-to-constants.md, data/blog/posts/2021/2021-01-18-smooth-upgrade-to-nette-31-in-diffs.md, data/blog/posts/2021/2021-01-25-introducing-composer-json-rector-rules.md, data/blog/posts/2021/2021-02-15-how-much-does-single-type-declaration-know.md, data/blog/posts/2021/2021-10-11-how-to-upgrade-annotations-to-attributes.md, data/blog/posts/2021/2021-10-18-how-all-frameworks-can-bump-to-php-81-and-you-can-use-older-php.md, data/blog/posts/2021/2021-12-31-new-in-rector-012-the-latest-php-in-a-single-import.md
- use new RectorConfig
- update notes
=> Make use of RectorConfig

composer.lock, ecs.php
- use new config
- use ECSConfig
=> Make use of RectorConfig and ECSConfig

data/blog/posts/2022/2022-01-21-how-to-migrate-legacy-php-applications-without-stopping-development-of-new-features.md, data/blog/posts/2022/2022-02-07-success-story-of-automated-framework-migration-from-fuelphp-to-laravel-of-400k-lines-application.md
I've changed my twitter account id (I didn't know that the redirect is not permanent...). 
I would appreciate it if you could deploy this when you have time! I'm not in a hurry with this fix.
=> fix 404 twitter link

data/blog/posts/2022/2022-04-26-new-in-rector-012-introducing-rector-config-with-autocomplete.md
Fixes https://github.com/rectorphp/rector/issues/7228.
=> Fix RectorConfig setlist name

assets/scss/app.scss, data/blog/posts/2022/2022-07-04-how-to-add-type-declarations-without-breaking-your-code.md, data/blog/posts/2022/2022-07-04-how-to-automatically-add-return-type-declarations-without-breaking-your-code.md, src/Controller/HomepageController.php, templates/homepage/homepage.twig
=> [blog] post certaint strict types

config/routes.php
**Before**
**After**
Fixes https://github.com/rectorphp/getrector.org/issues/630
=> Fix amnesia on routes.php config error

src/Controller/ForCompaniesController.php, templates/_snippets/menu.twig
**Before**
**After**
Fixes https://github.com/rectorphp/getrector.org/pull/692
=> Fix for-companies menu error 500

.gitignore
sub domains currently working on subdomains subdirectory, so I add subdomains to this.
=> add subdomains directory to .gitignore

composer.json, composer.lock, packages/Demo/Controller/DemoController.php, templates/demo/demo.twig
@TomasVotruba this is display Rector vesion at demo page:
=> Display Rector version at demo page

assets/scss/app.scss, composer.lock, data/blog/posts/2022/2022-09-09-support-for-nested-doctrine-annotation-to-flat-attributes-in-rector-014.md, packages/Demo/Controller/DemoController.php, src/Controller/CompanyCooperationController.php, src/ValueObject/Routing/RouteName.php, templates/homepage/company_cooperation.twig, templates/homepage/for_companies.twig, templates/homepage/homepage.twig
Closes https://github.com/rectorphp/getrector.org/issues/768
=> Bump deps + add company coop

data/docs/config-configuration.md, data/docs/ignoring-rules-or-paths.md, data/docs/static-reflection-and-autoload.md, src/Documentation/DocumentationMenuFactory.php
=> [docs] Add indent/spacing

data/blog/posts/2022/2022-12-10-new-in-rector-015-complete-safe-and-known-type-declarations.md
=> tv rector 15 type declarations

composer.lock
Ref https://github.com/symplify/coding-standard/releases/tag/11.1.26.72
=> Update to use latest symplify/coding-standard

assets/scss/app.scss, templates/_snippets/layout/footer.twig, templates/homepage/_parts/benefits.twig, templates/homepage/homepage.twig
Thanks @honzajavorek for screenshots!
=> tv feedback man support group

.github/workflows/code_analysis.yaml, assets/scss/app.scss, bin/only-rem-in-css.php, templates/_snippets/menu.twig, templates/blog/blog.twig, templates/homepage/_parts/benefits.twig
- [ci] add rem check
- less em
- remove few floats
- rss jump
- less em
- less em
- try percents
- less em
=> tv no em css

data/blog/posts/2021/2021-02-15-how-much-does-single-type-declaration-know.md
This will correct the namespace import for ParamTypeFromStrictTypedPropertyRector
=> Correct import namespace

README.md, src/Controller/HomepageController.php, templates/homepage/_parts/benefits.twig, templates/homepage/_parts/faq.twig, templates/homepage/homepage.twig
As requested, I've created this PR to submit some changes to the Rector home page. 
A couple things to note:
* For reference, I used the [APA Styleguide](https://apastyle.apa.org/style-grammar-guidelines/capitalization/title-case) for title-case
* I created a different commit with a single change or single-section change and explanation of my changes. This would allow you to accept the entire PR, or to only cherry pick certain things you'd like.
* I updated the readme to add `composer install` - which I'm sure you haven't had to do in a while. :)
I did not touch the `We help 5+ years PHP companies to get the most of the code they already have.` or the FAQ section. If you like this PR, I'd be willing to update those sections as well in a future PR. I just may need to open issues to get …
=> Suggested Homepage wording and capitalization changes

src/Controller/ContactController.php, src/Controller/ForCompaniesController.php, templates/homepage/_parts/faq.twig, templates/homepage/about.twig, templates/homepage/contact.twig, templates/homepage/hire_team.twig, templates/homepage/homepage.twig, tests/Acceptance/SupportPageCest.php
Based on the feedback from #1037 and other things I've found, here are the remaining proposed changes.
I did not review blog entries or documentation.
As before, I created many commits with some descriptions.  I probably put less explanation in each of the commit messages now, but let me know if you have any questions!
Closes #1037
=> 2023 feb wording changes

data/docs/custom-rule.md
@TomasVotruba this should fix #1044 :)
=> Remove nette/utils dependency in custom-rule.md

composer.json, composer.lock
Fixes https://github.com/rectorphp/getrector-com/issues/1054
=> Use rector:dev-main again

composer.json, composer.lock, packages/Blog/Repository/PostRepository.php, packages/Blog/Twig/RoutingTwigExtension.php, packages/Demo/Utils/FileDiffCleaner.php
I found a use case that it can be usefull for this, that can be used here to early check on search found, eg:
-  `Atleast::once()` usage on 
- packages/Blog/Twig/RoutingTwigExtension.php
- packages/Demo/Utils/FileDiffCleaner.php
-    `Finder::first()` usage on `packages/Blog/Repository/PostRepository.php`
=> Utilize ArrayLookup

resources/views/blog/post.blade.php, resources/views/demo/demo.blade.php, utils-tests/Laravelize/TwigToBladeConverter/Fixture/if_else_if.twig.inc, utils/Laravelize/TwigToBladeConverter.php
- format date time
- update
- condnitsio
=> Add format support

utils-tests/Rector/NodeFactory/SignaturePropertyFactory.php, utils-tests/Rector/Rector/Class_/SymfonyCommandToLaravelCommandRector/Fixture/configure_to_signature.php.inc, utils/Rector/Rector/Class_/SymfonyCommandToLaravelCommandRector.php, utils/config/rector_services.php
- already covnereted
- kick off command signature rule
=> Add Laravel Command Rector rule

resources/css/app.scss, resources/docs/how-rector-works.md, resources/views/_snippets/homepage_separator.blade.php, resources/views/demo/demo.blade.php
=> Second wave

resources/blog/posts/2023/2023-03-23-faster-rector-on-015.md
Hi @keulinho, this is blog post based on your performance improvements PRs. Thank you for the performance improvement PRs.
=> Add blog post for Faster Rector on 0.15.22

composer.lock, utils-tests/Rector/Rector/ClassMethod/SymfonyRouteAttributesToLaravelRouteFileRector/SymfonyRouteAttributesToLaravelRouteFileRectorTest.php, utils/Rector/Rector/ClassMethod/SymfonyRouteAttributesToLaravelRouteFileRector.php
Ref https://github.com/rectorphp/getrector-com/pull/1393#issuecomment-1585758237
=> Fix unit test of removed RemovedAndAddedFilesCollector

resources/docs/set-lists.md
Should be pretty self explanatory.
=> Fix broken PHP examples

resources/blog/posts/2023/2023-08-14-rector-017-brings-more-robuts-and-lighter-node-tree.md
- [post] no parent/next/previous node
- gram
=> [post] Rector 0.17 and robuts node tree

resources/blog/posts/2023/2023-08-21-rector-018-how-we-made-tests-seven-times-faster.md
Ref https://github.com/rectorphp/rector-src/pull/4827
=> [post] speed up tests 

src/DemoRunner.php
this fixes the php error for me. maybe it works for @samsonasik now?
I got a new error now
=> Fix "PHP command not found" error

src/DemoRunner.php
PHPStan for quick fix commit from server https://github.com/rectorphp/getrector-com/commit/7179151c827d77274c88eb09593dde2339328688
=> PHPStan fix

composer.json, composer.lock, rector.php, resources/css/app.scss, resources/views/homepage/_parts/faq.blade.php, src/Http/HttpKernel.php, storage/debugbar/.gitignore
Keep them focused, keep them slim :)
<br>
---
=> Tidy up faqs

resources/docs/troubleshooting-parallel.md
Hi all,
Thanks for making Rector, it's proved to be a very handy tool!
This pull request just makes a small change to the "Troubleshooting Parallel" documentation to improve the clarity on how you actually set these options.
=> Slightly improved the clarity of the parallel docs

src/Rules/ValidPhpSyntaxRule.php, src/Validator/PhpLinter.php, tests/Controller/DemoControllerTest.php
refs https://github.com/rectorphp/rector/issues/8170#issuecomment-1701087008
----
=> More explicit error message on invalid php code

resources/blog/posts/2024/2024-01-30-grab-a-fresh-book-release-with-rector-019.md, resources/blog/posts/2024/2024-01-30-grab-fresh-book-release-with-rector-019.md
- [post] book release
- fixup! [post] book release
=> tv book update

resources/docs/commands.md, resources/docs/import-names.md, resources/docs/static-reflection-and-autoload.md, src/Documentation/DocumentationMenuFactory.php
- add commands docs
- remove troubleshooting, finalize will be removed
=> [docs] add useful command section - tidy up

resources/blog/posts/2024/2024-01-30-grab-fresh-book-release-with-rector-019.md, resources/views/_snippets/layout/footer.blade.php, resources/views/_snippets/menu_items.blade.php, resources/views/homepage/hire_team.blade.php, resources/views/homepage/homepage.blade.php
=> [post] book release next

resources/docs/cache-in-ci.md
closes https://github.com/rectorphp/getrector-com/issues/2022
=> Improve GitHubActions default cache-keys

resources/docs/cache-in-ci.md
as discussed in https://github.com/rectorphp/rector/discussions/8357#discussioncomment-8420673
=> configure and create cacheDirectory

resources/docs/cache-in-ci.md, resources/docs/config-configuration.md, resources/docs/configured-rules.md, resources/docs/creating-a-node-visitor.md, resources/docs/custom-rule.md, resources/docs/define-paths.md, resources/docs/how-rector-works.md, resources/docs/how-to-run-on-php-53.md, resources/docs/ignoring-rules-or-paths.md, resources/docs/import-names.md, resources/docs/introduction.md, resources/docs/php-version-features.md, resources/docs/set-lists.md, resources/docs/static-reflection-and-autoload.md
Avoid copy paste and got error like in issue:
- https://github.com/rectorphp/rector/issues/8480
=> [Doc] Add missing <?php open tag in config example

resources/css/app.scss, resources/docs/commands.md, resources/docs/define-paths.md, resources/docs/set-lists.md, src/Documentation/DocumentationMenuFactory.php
Ref https://github.com/rectorphp/getrector-com/issues/2043
=> Improve post-Rector 1.0 docs

resources/docs/how-to-run-on-php-53.md
Ref https://github.com/rectorphp/rector/issues/8489
=> [docs] Remove named args from config for PHP 5.3

phpstan.neon, rector.php, resources/views/ast/ast.blade.php, resources/views/ast/ast_detail.blade.php, src/Http/Controller/Ast/AstDetailController.php, src/PhpParser/ClickablePrinter.php, src/PhpParser/PrinterHelper.php, src/Utils/ClickablePrinterBuilder.php
=> tv interactive form 3

src/Http/Request/DemoFormRequest.php, src/Rules/HasRectorRule.php, tests/Controller/DemoControllerTest.php
@staabm this should fix https://github.com/rectorphp/getrector-com/issues/2038
it is not perfect, but will make less notice
=> Validate at least 1 rector rule on Demo page

resources/views/demo/demo.blade.php
=> [DX] Add new line in each error shown on demo page for multi errors

rector.php, src/PhpParser/ClickablePrinter.php
`ClickablePrinter` seems ok to be executed by Rector, and tested `/ast` page still working fine.
=> Run Rector on ClickablePrinter

composer.json, composer.lock, resources/blog/posts/2024/2024-05-02-how-to-upgrade-zend-legacy-project.md, resources/css/app.scss, src/Utils/ClickablePrinterBuilder.php
- **bump**
- **[post] zend ugprade**
- **gram**
=> [post] zend upgrade

src/Http/Controller/Ast/AstDetailController.php, src/PhpParser/NodeResolver/FocusedNodeResolver.php
**Before**
**After**
Closes https://github.com/rectorphp/getrector-com/issues/2223
=> Fallback to dump all nodes instead of error on /ast/100000 when id is not exists

routes/web.php
=> validate routing uuid and active node id to avoid 500 error

composer.json, composer.lock, resources/blog/posts/2024/2024-05-22-migrate-datetime-to-carbon.md
- **[post] carbon**
- **misc**
- **gram**
=> [post] datetime to carbon

src/Controller/DocumentationController.php
=> Fix 500 internal server error on /documentation page

package.json, resources/views/_snippets/javascripts.blade.php, resources/views/base.blade.php, resources/views/homepage/filter-rector.blade.php, resources/views/livewire/rector-filter-component.blade.php, src/Controller/FilterRectorController.php, src/FileSystem/RectorFinder.php, src/Livewire/RectorFilterComponent.php, src/RuleFilter/ValueObject/RuleMetadata.php, yarn.lock
Everything works well :) except when the component is re-rendered, the hilightjs is lost.
I've triedy:
- using `@script`, doesn't work
- using `addEventListener` with various `livewire:*` events, doesn't work
[Screencast from 2024-06-04 22-12-43.webm](https://github.com/rectorphp/getrector-com/assets/924196/74aaff55-ea27-473f-900f-b42b53c0dfac)
Any ides how to make hljs re-atach after component is changed?
Olá @ijpatricio, I know we've done something like this together, but I don't have the project anymore. Any tips? :)
=> [filer] add diffs in livewire - step 3

phpstan.neon, resources/css/app.scss, resources/views/_snippets/menu_items.blade.php, resources/views/homepage/filter-rector.blade.php, resources/views/livewire/rector-filter-component.blade.php, src/Livewire/RectorFilterComponent.php, src/RuleFilter/MatchingScoreResolver.php, src/RuleFilter/RuleFilter.php
News :)
* https://x.com/VotrubaT/status/1802151509532278799
* https://x.com/VotrubaT/status/1802156105705165045
=> Improve filters

composer.json, composer.lock, phpstan.neon, resources/css/app.scss, resources/views/homepage/filter-rector.blade.php, resources/views/livewire/rector-filter-component.blade.php, src/Controller/FilterRectorController.php, src/Entity/RectorRun.php, src/Enum/NodeTypeToHumanReadable.php, src/Enum/RuleNodeRedirectMap.php, src/FileSystem/RectorFinder.php, src/Livewire/RectorFilterComponent.php, src/RuleFilter/RuleFilter.php, src/RuleFilter/ValueObject/RectorSet.php, src/RuleFilter/ValueObject/RuleMetadata.php, src/Sets/RectorSetsTreeProvider.php, src/ValueObject/AppliedRule.php
=> Filter - add sets

resources/css/menu.scss, resources/views/homepage/_parts/benefits.blade.php
=> tv play and learn 3

resources/views/livewire/ast-component.blade.php
=> [Ast Page] Fix new line before code after <?php opening tag

src/Validation/Rules/HasRectorRule.php
Register has rule validation on demo page
=> Add   withPhpPolyfill to HasRectorRule

resources/views/livewire/rector-filter-component.blade.php, src/Enum/NodeTypeToHumanReadable.php
Improving mobile view for `/find-rule`
=> improve mobile view for find rule

rector.php
Ref PR:
- https://github.com/rectorphp/rector-src/pull/6028
=> clean up skip config on rector.php

bin/generate-clickable-ast-printer.php, phpstan.neon, public/ecs.php, public/temp-ecs-file.php, rector.php, resources/views/_snippets/menu_items.blade.php, resources/views/homepage/rule-detail.blade.php, resources/views/livewire/rector-filter-component.blade.php, routes/web.php, src/Controller/RuleDetailController.php, src/FileSystem/RectorFinder.php, src/Logging/SearchLogger.php, src/PhpParser/SimplePhpParser.php, src/Providers/AppServiceProvider.php, src/RuleFilter/ConfiguredDiffSamplesFactory.php, src/RuleFilter/Markdown/MarkdownDiffer.php, src/RuleFilter/PhpParser/NodeFactory/RectorConfigFactory.php, src/RuleFilter/PhpParser/NodeVisitor/NameImportingNodeVisitor.php, src/RuleFilter/PhpParser/Printer/RectorConfigStmtsPrinter.php, src/RuleFilter/ValueObject/ConfiguredDiffSample.php, src/RuleFilter/ValueObject/RuleMetadata.php, src/Validation/PhpLinter.php, temp-ecs-file.php, tests/RuleFilter/Markdown/MarkdownDifferTest.php, tests/RuleFilter/PhpParser/Fixture/expected-config.php, tests/RuleFilter/PhpParser/RectorConfigStmtsPrinterTest.php
Add configuration example to copy-paste and try :) ↓
=> [rule-detail] Add rule detail page with examples of configuration

resources/views/_snippets/menu_items.blade.php, resources/views/homepage/rule-detail.blade.php, resources/views/livewire/rector-filter-component.blade.php, src/RuleFilter/ValueObject/RectorSet.php, src/RuleFilter/ValueObject/RuleMetadata.php
- **add new marker**
- **add rule count**
- **make code in description higlhighter**
=> Add menu highlight, rule count into set select and highligh code in rule description

.gitignore, src/FileSystem/RectorFinder.php, src/Livewire/RectorFilterComponent.php
- **search for commnity rules**
- **skip deprecated rules**
=> Skip deprecated rules in a filter

resources/views/homepage/rule-detail.blade.php, resources/views/livewire/rector-filter-component.blade.php, src/RuleFilter/PhpParser/NodeVisitor/NameImportingNodeVisitor.php, src/RuleFilter/ValueObject/RectorSet.php
**Before**
**After**
Fixes https://github.com/rectorphp/getrector-com/issues/2405
Fixes https://github.com/rectorphp/getrector-com/issues/2433
=> Fix rule-detail 500 error

phpstan.neon, resources/views/blog/post.blade.php, resources/views/homepage/rule-detail.blade.php, resources/views/livewire/rector-filter-component.blade.php, routes/web.php, src/Controller/Socials/PostThumbnailController.php, src/Controller/Socials/RuleThumbnailController.php, src/Enum/FontFile.php, src/Thumbnail/Enum/Color.php, src/Thumbnail/ThumbnailGenerator.php
Fix https://github.com/rectorphp/getrector-com/issues/2427
=> tv rule details png

src/Validation/Rules/HasRectorRule.php, tests/Controller/DemoControllerTest.php
**Before**
**After**
Fixes https://github.com/rectorphp/getrector-com/issues/2438
=> Fix undefined method some() on RectorConfigBuilder

.github/workflows/code_analysis.yaml, src/Request/RectorRunFormRequest.php, tests/Controller/DemoControllerTest.php
it cause error on server
will check directly on server.
=> Temporary disable ForbiddenCallLikeRule as cause error on getrector.com/demo

.github/workflows/code_analysis.yaml, src/Request/RectorRunFormRequest.php, src/Validation/Rules/ForbiddenCallLikeRule.php
Fix for https://github.com/rectorphp/getrector-com/pull/2457
that was cause error
=> Fix server error from ForbiddenCallLikeRule

tests/Controller/DemoControllerTest.php
Ref https://github.com/rectorphp/getrector-com/pull/2458
=> Re-enable test on DemoControllerTest

src/Entity/AbstractRectorRun.php
Ref https://github.com/rectorphp/getrector-com/pull/2435#pullrequestreview-2215406132
Fixes https://github.com/rectorphp/getrector-com/issues/2486
**Before**
**After**
=> [Demo] Fix crash no change on demo page

rector.php, resources/css/app.scss, resources/views/homepage/codebase-renovation.blade.php, routes/web.php, src/Controller/CodebaseRenovationController.php, src/Repository/RenovationItemRepository.php, src/ValueObject/RenovationItem.php, src/functions.php
Sometimes it's hard to visualize how do we handle upgrade from bare words.
This package will show before / after case study on common project we handle, so readers can see what we really do :+1:
=> [page] codebase rennovation - kick off, local only

rector.php, resources/views/homepage/codebase-renovation.blade.php, src/Repository/RenovationItemRepository.php
=> tv renovation 2

resources/views/homepage/interactive.blade.php, routes/web.php
- **enable link**
- **publish routes**
=> Silently publish custom rules :)

resources/docs/ignoring-rules-or-paths.md
Fixes https://github.com/rectorphp/rector/issues/8770
=> [doc] Fix documentation skip method

resources/views/livewire/step-by-step-component.blade.php, resources/views/step_by_step/_standalone/rector-config.blade.php, src/Enum/StepBreakpoint.php, src/Livewire/StepByStepComponent.php
Ref https://github.com/rectorphp/getrector-com/issues/2528
=> [step-by-step] Use buttons :)

resources/docs/introduction.md, resources/docs/set-lists.md
=> RE: #2547 - when referencing PHP 7.3 ensure example code is compatible

resources/docs/set-lists.md
=> Correct method name

.meta/oss-pledge.json, resources/blog/posts/2024/2024-09-09-rector-is-joining-open-source-pledge.md, resources/views/blog/post.blade.php, resources/views/homepage/about.blade.php
Ref https://osspledge.com/join/
=> [post] Joining OSS Pledge

resources/views/livewire/step-by-step-component.blade.php
=> wider for better mobile look

resources/blog/posts/2024/2024-05-29-5-tricks-to-write-better-custom-rules.md
tested at https://getrector.com/custom-rule/e2629342-0432-4b77-aaa2-8f8c5808b87d
=> Bug missing negation on blog post 5 Tricks to Write Better Custom Rules

resources/blog/posts/2024/2024-11-13-introducing-composer-version-based-sets.md, resources/blog/posts/2024/2024-11-13-package-version-based-sets.md, resources/docs/composer-based-sets.md, resources/docs/custom-set-provider.md, src/Documentation/DocumentationMenuFactory.php
Post and docs for https://github.com/rectorphp/rector-src/pull/6428
Ref https://github.com/rectorphp/rector-src/pull/5976
=> [post] [docs] Add composer based sets

resources/docs/custom-set-provider.md
Fixes https://github.com/rectorphp/rector/issues/8951
=> Fix link composer-based-sets documentation

composer.json, composer.lock, phpstan.neon, resources/css/app.scss, resources/views/_snippets/form/form_textarea.blade.php, resources/views/_snippets/menu_items.blade.php, resources/views/ast/ast.blade.php, resources/views/ast/ast_detail.blade.php, resources/views/livewire/ast-component.blade.php, routes/web.php, src/Ast/Controller/AstController.php, src/Ast/Controller/AstDetailController.php, src/Ast/Controller/ProcessAstFormController.php, src/Ast/PhpParser/ClickablePrinter.php, src/Livewire/AstComponent.php, src/PhpParser/NodeFactory/ClickablePrinterNodeFactory.php, src/Repository/AstRunRepository.php
and
---
<br>
<br>
---
<br>
<br>
=> [Ast] Make AST-view form simpler

composer.lock, resources/blog/posts/2025/2025-03-03-how-to-strangle-your-project-with-strangle-anti-pattern.md, resources/views/blog/blog.blade.php, resources/views/blog/post.blade.php, resources/views/homepage/contact.blade.php, src/Ast/Request/AstFormRequest.php, src/Controller/Blog/BlogController.php
- **[post] strangle antipattern**
- **gram**
=> [post] strangler anti-pattern

composer.json, composer.lock, src/FileSystem/RectorFinder.php
ensure make compatible with latest rector.
=> Bump to PHPStan ^2.1.8

composer.lock
Fixes https://github.com/rectorphp/getrector-com/issues/2929
Ref https://github.com/rectorphp/rector-phpunit/commit/3158fa9914fde1401a15259ac637416d2c554975
=> Fix find rule page

src/Controller/RuleDetailController.php
To show highlight on code, ref https://github.com/rectorphp/getrector-com/pull/2984#pullrequestreview-2801559186
=> Set codeMirror => true on RuleDetailController

src/Ast/Controller/AstDetailController.php
=> Add codeMirror => true, on AstDetailController

resources/views/_snippets/javascripts.blade.php
Fix menu not clickable on homepage /
Fixes https://github.com/rectorphp/getrector-com/issues/3001
=> Fix bootstrap menu not loaded on homepage / that cause menu not clickable

.github/workflows/code_analysis.yaml, composer.json, composer.lock, resources/docs/jack.md, resources/docs/swiss-knife.md
- **[docs] jack**
- **[docs] add jack, add jack package**
- **[ci] add rector jack**
=> [docs] add jack, add jack package

.github/workflows/code_analysis.yaml, .github/workflows/daily_pull_request_automatic_update.yaml, .github/workflows/rector.yaml, .github/workflows/unit_tests.yaml, composer.json, composer.lock, src/Providers/AppServiceProvider.php, src/RuleFilter/PhpParser/Printer/RectorConfigStmtsPrinter.php, tests/AbstractTestCase.php, tests/Controller/DemoControllerTest.php, tests/DemoRunnerTest.php, tests/GitHubMagicLink/BodyFactory/FixtureBodyFactory/FixtureBodyFactoryTest.php, tests/GitHubMagicLink/BodyFactory/IssueBodyFactory/IssueBodyFactoryTest.php, tests/GitHubMagicLink/BodyFactory/PullRequestDescriptionFactory/PullRequestDescriptionFactoryTest.php, tests/GitHubMagicLink/LinkFactory/FixtureLinkFactory/FixtureLinkFactoryTest.php, tests/GitHubMagicLink/LinkFactory/IssueLinkFactory/IssueLinkFactoryTest.php, tests/RuleFilter/PhpParser/RectorConfigStmtsPrinterTest.php, tests/Validator/ErrorMessageNormalizerTest.php
Since server is using php 8.4 now, I think we can upgrade to php 8.4 for web requirement as well.
=> Upgrade to use php 8.4
