- src/Process/RectorProcessRunner.php
> Show error when invalid process output instead of „Syntax error“

- bin/run-demo.sh
In current version, the analysed file is not included anymore. 
To prevent broken scope of side-effect files.
This fixes the change, see https://github.com/rectorphp/rector#extra-autoloading
> add missing autoload path

- assets/scss/app.scss
- packages/demo/src/Entity/RectorRun.php
- templates/demo/demo.twig
> Show used rector version on demo runs

- src/Twig/RectorCountVariableProvider.php
This should fix https://github.com/rectorphp/getrector.org/issues/186
However, I didn't test it at all because I was not sure how
I also changed the fallback count to 600? The real count is 625 right now if my regex is correct
> Fix the count

- templates/demo/demo.twig
> Show fatal error message with newlines

- templates/demo/demo.twig
When working on small screens, it's very easy to mis the error messages as they are located under the Process button.
This is also why it took me some time to know that the Demo was broken (#270).
This will improve it.
> Demo > Show failure always on top

- packages/demo/src/Utils/FileDiffCleaner.php
- packages/demo/tests/Utils/Fixture/multiple_classes.txt
- packages/demo/tests/Utils/Fixture/start_input.txt
See #245
I tried to fix this but it's not as easy. The regex always looks for the last part of the diff.
Wouldn't it be better to just show the full diff of the file? Or just show the full content of the changed file? Maybe side by side?
> Multiple classes diff is wrong

- .github/workflows/daily_pull_request_automatic_update.yaml
- composer.lock
- Use `--with-all-dependencies` for composer update rector/rector as currently phpstan requirement is pinned.
https://github.com/rectorphp/rector/blob/000c27be3b4528b45105437aee3a6685d899a2be/composer.json#L10
Also update composer.lock to update to latest version for its updated both rector and phpstan.
> [Daily PR] Use --with-all-dependencies for composer update rector/rector

- .github/workflows/daily_pull_request_automatic_update.yaml
- composer.lock
To avoid error in latest GHA: 
```bash
Loading composer repositories with package information
7
Updating dependencies
8
Your requirements could not be resolved to an installable set of packages.
9
10
Problem 1
11
- Root composer.json requires symplify/amnesia 9.4.22, found symplify/amnesia[9.4.22] but the package is fixed to 9.4.11 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.
12
Problem 2
13
- Root composer.json requires symplify/autowire-array-parameter 9.4.22, found symplify/autowire-array-parameter[9.4.22] but the package is fixed to 9.4.11 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.
14
Problem 3
15
- Root …
```
> [Daily PR] Include symplify/ packages on composer update rector/rector

- .github/workflows/daily_pull_request_automatic_update.yaml
The simplify/* packages are pinned with version 9.4.22
https://github.com/rectorphp/getrector.org/blob/28fe90b6c1aae941fddfe3458d10c9586980b36e/composer.json#L46-L58
and already synced with composer.lock
> [Daily PR] Clean up symplify/* packages include in composer update

- composer.lock
@TomasVotruba let's try re-update back to rector 0.12.9 as the `remove sensio fw` was the reason the demo page was error https://github.com/rectorphp/getrector.org/issues/461#issuecomment-999191625
> Re-update back to rector 0.12.9

- composer.json
- composer.lock
- config/bundles.php
- packages/Demo/Controller/DemoController.php
- yarn.lock
The only feature we use from the sensio framework bundle extra is entity resolution. It will be added to Symfony 6.1 possibly:
https://github.com/symfony/symfony/pull/43854
Removing the bundle before fix causes  this error:
---
<br>
For now, we can add 2 lines to fetch entity explicitly. That way code is more clear and we can drup full package that is about to be deprecated... and not even supported by Symfony 6 :+1: 
@samsonasik Could you verify locally this PR works well for you? I've tested demo, found an exception and fixed it this time. Just to be sure before merge :)  Than you
> Remove sensio if possible

- composer.json
- composer.lock
as composer.json using `rector/rector` `dev-main`, PHPStan need to use PHPStan ^1.5.6 in composer.lock and composer.json due to https://github.com/rectorphp/rector-src/pull/2014
> Update to use latest PHPStan ^1.5.6

- templates/_snippets/menu.twig
When user open different page, eg: `/blog`, then click `First Run` link, it currently only append `#first-run` instead of go to home page with `#first-run` id: `https://getrector.org/blog#first-run`. 
This PR fix it.
> Fix First Run link linked when open from non homepage

- .github/workflows/daily_pull_request_automatic_update.yaml
- composer.lock
The current command will get the following output:
```bash
composer update rector/rector --with-all-dependencies
Gathering patches for root package.
Loading composer repositories with package information
Info from https://repo.packagist.org: #StandWithUkraine
Updating dependencies
Your requirements could not be resolved to an installable set of packages.
Problem 1
- Root composer.json requires rector/rector dev-main -> satisfiable by rector/rector[dev-main].
- symplify/phpstan-rules 10.3.0 requires phpstan/phpdoc-parser ^1.6.0 -> satisfiable by phpstan/phpdoc-parser[1.6.0].
- rector/rector dev-main conflicts with phpstan/phpdoc-parser <1.6.2.
- symplify/phpstan-rules is locked to version 10.3.0 and an update of this package was not requested.
```
updated to : 
```
composer update …
```
> Add phpstan-phpdoc-parser to daily update

- .github/workflows/daily_pull_request_automatic_update.yaml
The deployment in getrector.org is already per-6 hours: 00:05, 06:05, 12:05, 18:05.
This PR update the daily Update Rector Dependencies per 00:00, 06:00, 12:00, 18:00.
The 5 minutes different is to ensure PR merged first.
> Make daily pull request per 6 hours

- .gitignore
Reverts rectorphp/getrector.org#712
subdomain now can live outside root website.
> Revert "add subdomains directory to .gitignore"

- composer.json
- composer.lock
@TomasVotruba your commit https://github.com/rectorphp/getrector.org/commit/58f6f0e60df141909df605b0702fbf1c7cd4f4ab was update to use rector ^0.14, that will make per-6 hours update not applied as will wait for next release.
This PR update back to use dev-main to get faster feedback after fix applied to dev-main.
> Update back rector to use dev-main

- .github/workflows/acceptance_test.yaml
To ensure it mimic the production build which the scripts (css and js) are minified.
> [Test] Using yarn build instead of yarn run dev for acceptance test

- composer.lock
- data/blog/posts/2022/2022-08-05-separating-typo3-and-nette-as-community-packages.md
- data/blog/posts/2022/2022-11-08-separating-laravel-and-cakephp-as-community-packages.md
- packages/Blog/FileSystem/PathAnalyzer.php
- packages/Blog/Repository/PostRepository.php
- packages/Blog/Twig/RoutingTwigExtension.php
- packages/Blog/ValueObject/Post.php
- packages/Blog/ValueObjectFactory/PostFactory.php
- packages/Demo/Error/ErrorMessageNormalizer.php
- src/Twig/TitleTwigExtension.php
- src/Utils/StringsConverter.php
Related PRs in Rector:
* https://github.com/rectorphp/rector-src/pull/2966
* https://github.com/rectorphp/rector-cakephp/issues/27
* https://github.com/rectorphp/rector-src/pull/3019
<br>
Huge thanks :heart:  :heart:  :heart:  for making this happen to  @driftingly and [samsonasik](https://github.com/samsonasik) :clap:
> [post] laral cake php comunity

- data/blog/posts/2022/2022-07-04-how-to-automatically-add-return-type-declarations-without-breaking-your-code.md
This fixes the suggested config by adding the missing opening tag and the missing closing bracket and semi-colon. Now if the example is copied and pasted into a `rector.php` file it works straight out of the box.
> Fix final config suggestion

- data/docs/how-rector-works.md
I can't find the `reconstruct ` method in the rector source code. After checking the `Custom Rule` page I guess the `refactor` method is meant. 
If I'm wrong some explanation would be fine :)
> Use correct method name

- data/docs/custom-rule.md
- data/docs/writing-tests-for-custom-rule.md
- src/Documentation/DocumentationMenuFactory.php
I noticed while I was creating a custom rule that there was no good documentation on how to write tests, only a recommended file structure without clarification. There is an implicit expectation that tests are simply copied from existing rules.
It is debatable whether this needs to be documented explicitly, because documentation can get out of date, or whether the documentation for recommended file structure should explicitly mention the expectation of copying from existing rules. If you prefer to not document writing tests for custom rules, let me know and I'll create a PR for making the expectation explicit.
While describing `provideData`, I wanted to link to another page (How to add test case) as the structure and logic of the Fixture files was already described elsewhere. However, …
> Add documentation on how to write tests for custom rules.

- data/docs/reporting-issue-with-rector.md
- src/Documentation/DocumentationMenuFactory.php
As discussed in #1073 
Also added a leading statement to explain why a test case in a pull request is needed.
> Rename the "How to add test case" page

- resources/docs/introduction.md
Mentioning `vendor/bin/rector init` on rector below 0.17 sometime seems unreadable, user just copy paste and create issue why it not working.
Instead, this PR update to use `vendor/bin/rector` and show it will prompt generated config.
> [Doc] Update generate "rector.php" config via vendor/bin/rector

- resources/docs/creating-a-node-visitor.md
since we use `Laravel` DI, the `services()->tag()` no longer works, in this PR, I updated to use Laravel code.
```php
$rectorConfig->singleton(HelloVisitor::class);
$rectorConfig->tag(HelloVisitor::class, ScopeResolverNodeVisitorInterface::class);
```
It can be merged when next rector released.
> [Doc] Update documentation to use Laravel code for register custom Node Visitor service

- .github/workflows/code_analysis.yaml
- .github/workflows/daily_pull_request_automatic_update.yaml
- .github/workflows/rector.yaml
- .github/workflows/unit_tests.yaml
- resources/blog/posts/2020/2020-10-05-how-to-make-rector-contribute-your-pull-requests-every-day.md
- resources/blog/posts/2020/2020-11-30-smooth-upgrade-to-php-8-in-diffs.md
Current github actions/checkout v3 got error:
```
Download action repository 'actions/checkout@v3' (SHA:f43a0e5ff2bd294095638e18286ca9a3d1956744)
Error: Can't use 'tar -xzf' extract archive file: /home/runner/work/_actions/_temp_4ecd32f5-c361-435e-b74b-7171ccb18414/3c125ce6-395a-4023-acd8-39fc47eba947.tar.gz. return code: 2.
```
Ref https://github.com/rectorphp/rector-src/actions/runs/6074243601/job/16477779233#step:1:35
It reported at:
- https://github.com/actions/checkout/issues/1448
This PR try to update to github actions/checkout v4.
> Update github actions/checkout from v3 to v4

- resources/docs/custom-rule.md
@TomasVotruba @staabm Regex support on `isName()` is removed at PR:
- https://github.com/rectorphp/rector-src/pull/4954
This PR update documentation to use directly `fnmatch()`
> [Doc] Use fnmatch() instead of $this->isName($node->name, 'set*') in docuemntation create custom rule

- resources/docs/custom-rule.md
Continue of PR:
- https://github.com/rectorphp/getrector-com/pull/1654
this PR clean up `getName()` usage.
> [Doc] Clean up getName() usage on custom-rule.md

- resources/demo/DemoFile.php
- resources/demo/demo-config.php
I think for an end-user its more suprising and compelling to see rector inferring types instead of detecting/removing dead code
> Use SetList::TYPE_DECLARATION in demo defaults

- resources/docs/import-names.md
The new `RectorConfig::configure()` method requires `withImportNames() ` method instead of `importNames()`.
> Use withImportNames() method

- src/Rules/FuncCallRule.php
- tests/Controller/DemoControllerTest.php
@staabm this fix https://github.com/rectorphp/getrector-com/issues/2012
> Fix missing semicolon warning on demo config page

- resources/docs/how-rector-works.md
This makes the highlighting colors look unnatural.
> [Doc] Add missing ; in config example

- resources/docs/debugging.md
hey, imho its better to keep it clean of a 404 notif when devs arrived on the page
> chore(doc): remove not found demo path

- src/Http/Request/DemoFormRequest.php
- src/Rules/ShellExecRule.php
- tests/Controller/DemoControllerTest.php
Avoid user input danger execution operator as `ShellExec`
```php
<?php `dangerous command`; ?>
```
Ref https://www.php.net/manual/en/language.operators.execution.php
> [Demo Validation] Add ShellExecRule rule to avoid `` execution operator usage on rector config input

- resources/docs/introduction.md
On php 7.x, the named argument is not yet exists, this update doc to clarify it.
Ref https://github.com/rectorphp/rector/issues/8653
/cc @orionseye
> [Docs] Add note for withPreparedSets() on php 7.x

- resources/views/_snippets/styles.blade.php
- resources/views/base.blade.php
added setTimeout with 0 to run this function after rendering so that it works properly. (POV: I faced this kind of issue a lot after the new update)
also updated `highlightBlock` to `highlightElement` to remove the deprecation warning.
https://github.com/rectorphp/getrector-com/assets/53343069/b6399010-90d5-44b8-bc92-83d94498d8b3
> Feat: hljs after re render

- src/Request/DemoFormRequest.php
- src/Validation/Rules/IncludeRule.php
- tests/Controller/DemoControllerTest.php
I tried add `include "index.php";` on demo box config, and it got error as it include the index page itself:
**Before**
-------
I add `IncludeRule` to safe it:
**After**
-----
> [Demo] Add IncludeRule for demo box config

- rector.php
Tested locally:
**Before** stuck at 69%
```
➜  getrector.org git:(main) vendor/bin/rector process --clear-cache                                            
74/106 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓░░░░░░░░░]  69%
```
**After** make 100%
```
➜  getrector.org git:(skip-ide-helper) vendor/bin/rector process --clear-cache
105/105 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓] 100%
[OK] Rector is done!                                                                                                   
```
It seems generated code for Laravel 11.11.0 and ignored by git so not necessarily to scan:
https://github.com/rectorphp/getrector-com/blob/b3180f9b0f2fa4bf810d437fa657104feaefda23/.gitignore#L40
> [Config] Skip _ide_helper.php on rector.php as cause infinite loop

- resources/views/homepage/rule-detail.blade.php
- src/RuleFilter/ConfiguredDiffSamplesFactory.php
- src/RuleFilter/MatchingScoreResolver.php
- src/RuleFilter/PhpParser/NodeFactory/RectorConfigFactory.php
- src/RuleFilter/PhpParser/NodeVisitor/ConstantToValueNodeVisitor.php
- tests/RuleFilter/PhpParser/Fixture/expected-configured-config.php
- tests/RuleFilter/PhpParser/RectorConfigStmtsPrinterTest.php
- tests/Validator/ErrorMessageNormalizerTest.php
Instead of long constant import with self/class meshup, use simple string :+1:
> [rule-find] Improve printed config for constant values

- src/DemoRunner.php
DemoRunner currently always create new directory without removal, and only remove files inside it, that cause a lot of empty directories:
this patch fix it.
> [Demo] Remove generated directory config on DemoRunner::processFilesContents()

- src/Validation/Rules/HasRectorRule.php
this ensure no overlapped consecutive request on rector demo page, also, if generated config no longer used, directly removed.
> [Validation] Randomize and delete after unused for generated rector config on HasRectorRule

- src/Request/RectorRunFormRequest.php
- src/Validation/Rules/ShortPhpConfigRule.php
- src/Validation/Rules/ShortPhpContentsRule.php
- src/Validation/Rules/ShortPhpLines.php
- src/Validation/Rules/ShortPhpLinesTrait.php
Currently, there short maximum lines = 100 is on php contents, but on php config, it doesn't have this validation.
This PR add `ShortPhpConfigRule` for config rule, which the config validation config box, which shared with "Create custom rule" page to avoid too many lines added on the page.
This `ShortPhpConfigRule` have 200 lines maximum.
> [validation] Add ShortPhpConfigRule

- resources/views/homepage/rule-detail.blade.php
- resources/views/livewire/rector-filter-component.blade.php
When you are searching for rules in the rule finder page and you find a rule which belongs to a set, you may want to know which other rules belong to that set.
In this PR we add links to the red badges with the set names which will take you straight to a list of all the rules that belong to that set
> Add links to rector sets from the filter results and rule detail pages

- resources/docs/cache-in-ci.md
I can see in a project that actions/cache v3 got 2 minutes on "post cache", while actions/cache v4 got 3 seconds, so it may actions/cache v4 has some bug fix included, also recommend to use latest versions of actions/cache
> [Doc] Update cache in CI to use actions/cache@v4

- resources/blog/posts/2024/2024-09-11-improving-rector-performance.md
@TomasVotruba as agreed here is my blog post about Improving Rector Performance. Please take a look and let me know if there is anything that needs changing. Please also let me know once this is live. Thanks!!
> Improving Rector Performance blog post

- src/FileSystem/RectorFinder.php
The `findBySlug()` should locate both core and community.
Fixes https://github.com/rectorphp/getrector-com/issues/2589
> Fix find rule community detail rule

- resources/views/_snippets/menu_items.blade.php
- resources/views/homepage/find_rule.blade.php
- resources/views/livewire/find-rule-component.blade.php
- src/Controller/FindRuleController.php
- src/FileSystem/RectorFinder.php
> [dx] Add rule counter to /find-rule

- resources/css/app.scss
- resources/docs/integration-to-new-project.md
- resources/docs/levels.md
- resources/docs/set-lists.md
- src/Documentation/DocumentationMenuFactory.php
- src/Markdown/GithubMarkdownConverter.php
- src/Thumbnail/ThumbnailGenerator.php
- src/functions.php
Closes https://github.com/rectorphp/getrector-com/issues/2771
> add separate level docs

- resources/docs/levels.md
> Fix documentation level, it start from 0

- composer.json
- composer.lock
- src/Enum/FindRule/GroupName.php
- src/Livewire/FindRuleComponent.php
- src/RuleFilter/ValueObject/RuleMetadata.php
- tests/RuleFilter/RuleFilterTest.php
When filtering the rules in the [Find Rule](https://getrector.com/find-rule?activeRectorSetGroup=laravel) page, the Laravel group only shows 38 rules, while there are 76 available at the moment. That happens because we only show and count the Laravel rules that belong to a set, as with the rest of the Rector groups.
That leaves out most of the Laravel rules.
In this PR we:
- Add an exception when filtering by Group, to check if the rule class starts with `RectorLaravel`
- Add `RuleFilterTest` to cover the edge case
- Use `dev-main` for the Laravel Rector rules, since rules can be available before we do a release
- Add the `LARAVEL` group name and replaces the string literal uses
Let me know please if this is OK or I need to change something.
And thank you for making the code open for the …
> Fix Laravel rule filtering

- composer.json
- composer.lock
`driftingly/rector-laravel` requirement should use tagged version which downgraded to php 7.2 https://github.com/driftingly/rector-laravel/tree/2.0.2
Fixes https://github.com/rectorphp/getrector-com/issues/2826
> Fix /find-rule 500 error

- resources/views/ast/ast.blade.php
**Before**
**After**
I am not good at css, but here we go :)
> Fix mobile show "parse" button on /ast page

- resources/docs/levels.md
See https://github.com/rectorphp/rector-src/pull/6695
> Add withCodingStyle() info to the docs

- resources/views/_snippets/form/form_diff.blade.php
- resources/views/_snippets/form/form_fatal_errors.blade.php
- resources/views/demo/demo.blade.php
- src/FileSystem/RectorFinder.php
Current solution uses `position: absolute` that disallows clearing div. That's why code overflows to next element.
The only path nows seems spliiting into 2 columns: one with origin code and 2nd with diffs.
Closes https://github.com/rectorphp/getrector-com/issues/2957
> [demo] Split code and diffs into 2 separate columns to avoid overflow

- resources/docs/run-single-rule.md
- src/Documentation/DocumentationMenuFactory.php
closes https://github.com/rectorphp/getrector-com/issues/2921 (ref https://github.com/rectorphp/rector-src/pull/6441)
> [docs] add --only option

- resources/views/_snippets/menu_items.blade.php
- resources/views/_snippets/styles.blade.php
Avoid error undefined `theme` javascript error, as only when codeMirror is set. 
```
[localhost:8000:56:22](http://localhost:8000/)
Uncaught TypeError: theme is null
toggleTheme http://localhost:8000/:72
onclick http://localhost:8000/:1
```
> Only show Dark/Light Theme bottom menu when on @isset ($codeMirror)

- resources/views/_snippets/menu_items.blade.php
- resources/views/_snippets/styles.blade.php
@TomasVotruba per review:
- https://github.com/rectorphp/getrector-com/pull/3006#issuecomment-2842744935
The id="theme-link" needs to be exists to avoid error:
```
[localhost:8000:56:22](http://localhost:8000/)
Uncaught TypeError: theme is null
toggleTheme http://localhost:8000/:72
onclick http://localhost:8000/:1
```
> Re-add Dark/Light Theme link

- .gitignore
- resources/json-database/upcoming_talks.json
- resources/views/homepage/_parts/posts.blade.php
- resources/views/homepage/_parts/upcoming_talks.blade.php
- resources/views/homepage/homepage.blade.php
- src/Controller/HomepageController.php
> [homepage] add simple overview of upcoming talks about rector

- resources/docs/composer-based-sets.md
- resources/views/llm/llms-txt.blade.php
- routes/web.php
- src/Controller/DocumentationController.php
- src/Controller/Llm/LlmsTxtController.php
- src/Documentation/DocumentationMenuFactory.php
- src/Documentation/DocumentationMenuItem.php
- src/Documentation/DocumentationMenuItemFactory.php
- src/Repository/PostRepository.php
- tests/Documentation/DocumentationMenuFactoryTest.php
Closes https://github.com/rectorphp/getrector-com/issues/2991
> [llm] kick of llms.txt

- resources/json-database/faqs.json
- resources/views/homepage/_parts/faq.blade.php
- resources/views/livewire/find-rule-component.blade.php
- src/Controller/HomepageController.php
> [homepage] Improve FAQs

- resources/css/app.scss
- resources/json-database/references.json
- resources/views/_snippets/javascripts.blade.php
- resources/views/hire_team/references.blade.php
- resources/views/homepage/_parts/faq.blade.php
- resources/views/homepage/homepage.blade.php
> [homepage] improve quotes

- resources/views/homepage/hire_team.blade.php
> [hire-team] update page and make more lean

- resources/default-form-data/demo/demo-config.php
- resources/views/demo/demo.blade.php
> [Demo] Add "Tips" config to demonstrate rule on specific PHP version

- resources/docs/troubleshooting-preload.md
- src/Documentation/DocumentationMenuFactory.php
@ostrolucky @TomasVotruba this is new documentation section for troubleshooting preload conflict on phpunit 12+
Ref 
- https://github.com/rectorphp/rector/issues/9242
- https://github.com/ostrolucky/rector-rules/pull/44
> [Docs] Add docs for troubleshoot preload conflict on phpunit 12+

- .github/workflows/daily_pull_request_automatic_update.yaml
To avoid miss update like this PR:
- https://github.com/rectorphp/getrector-com/pull/3226
also, `phpstan/phpdoc-parser` is not in dependencies, so can be removed.
```
➜  getrector-com git:(bump-php-parser) composer show phpstan/phpdoc-parser
In ShowCommand.php line 325:
Package "phpstan/phpdoc-parser" not found, try using --available (-a) to show all available packages.                                                                                                 
```
> Add nikic/php-parser to composer update on daily pull request update

- resources/views/_snippets/layout/footer.blade.php
It seems to me that the footer should be at the very bottom of the page.
I suggest we fix this
> Fix footer position

- resources/views/livewire/find-rule-component.blade.php
- src/FileSystem/RectorFinder.php
- src/Livewire/FindRuleComponent.php
- src/RuleFilter/RuleFilter.php
- src/RuleFilter/ValueObject/RuleMetadata.php
Hello!
Closes https://github.com/rectorphp/rector/issues/9299, closes https://github.com/driftingly/rector-laravel/issues/342
It has been very difficult to discover rules that are not a part of any set (unless you just happening to be searching the name). This PR adds a `Rules not in set` pseudo-selector that will show all of the rules in a group that are not in a set.
<details>
<summary>Screenshots</summary>
</details>
Additionally, I made a performance improvement to help filter sets faster.
Thanks!
> feat: add ability to discover rules not in a set
